agentAddress udp:161
rocommunity public
sysLocation Cybersecurity Training Lab - 0uiKwKIDOMK3bcAxWG4eVEQu8z2GKONM
sysContact training@example.invalid
sysName enum-iot-01
sysDescr Training IoT-style SNMP endpoint
